version: '3.7'
services:
  app:
    container_name: grant-connect-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    env_file:
      - ./.env
